### ISSUE TITLE
0.4 processes docs are broken

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-processes-docgen#15]
https://openeo.org/documentation/0.4/processes.html looks broken: 
all process parameter lists are empty (both under "Description" as under "Parameters"). Return values also look strange.

For example load_collection:
![Screenshot from 2021-06-22 17-24-13](https://user-images.githubusercontent.com/44946/122953328-ebc79e00-d37e-11eb-9be5-0cd112caebe3.png)

**Comment by m-mohr** [comment]
Yes, indeed, there's a bug in the migration process of the DocGen (and a minor one in the Vue components). I've just fixed it in dev, but will wait for the next Vue component release in the next days and then I'll release a new DocGen version.

**Comment by soxofaan** [comment]
yes no hurry, nobody is looking at 0.4 anymore  (or shouldn't be)  I guess

**Comment by m-mohr** [comment]
Actually, I released on a dev version of the Vue components as all other changes are unrelated to the Processes. Should deploy to processes.openeo.org/0.4.2 etc and openeo.org itself within the next 1 or 2 days.
