### ISSUE TITLE
Bug in SchemaElement when array accepts more than one data type

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-processes-docgen#2]
Rendering in *SchemaElement.vue* has a bug when "un-collapsing" the *Items* property of an array that accepts more than one data type.

---

Example: The `filter_daterange` process when rendering the [`/processes` output of the Earth Engine driver](http://earthengine.openeo.org:8080/v0.3/processes). Screenshot of the case where I stumbled upon this:

![grafik](https://user-images.githubusercontent.com/17781682/49388363-151e7100-f724-11e8-9916-219324007d1c.png)

Clicking those dots results in:

> TypeError: "this.schema.type.toLowerCase is not a function"

And indeed: `this.schema.type` is not a string, but an array:

![grafik](https://user-images.githubusercontent.com/17781682/49388477-4eef7780-f724-11e8-8c74-697624b0eca3.png)

---

The stack trace points to the function `showRow` - this is the line where it happens:

https://github.com/Open-EO/openeo-processes-docgen/blob/b2e81234e63a5850dbf344a21f6b8e54a0a5d055/src/components/SchemaElement.vue#L150

I suggest changing the bad instruction

`['object', 'array'].includes(this.schema.type.toLowerCase())`

to

`[].concat(this.schema.type.toLowerCase()).some(e => e=='object' || e=='array')`

The `concat` to an empty array makes sure that we either keep the array as it was or convert the `"string"` to `["string"]`, so that we always have an array that we can test against with `some`.

---

But I don't know whether that would fully fix the entire problem, or whether there's more logic that still expects `type` to always be an array and should therefore be updated too.

**Comment by m-mohr** [comment]
Good catch. Fixed by explicitly checking for a string.
For an array of types the format is not well defined anyway.
